git:
  submodules: false

language: go
os: linux
sudo: enabled

env:
  - GO111MODULE=on

go:
  - 1.16.3

before_install:
  - sudo apt-get update
  - sudo apt-get -y install unbound libunbound-dev

script:
  - make bin
  - make test

