#!/bin/bash

## Check enviroment
if [ -z "$PHY" ]; then
  echo "Enviroment variable(PHY) is NULL"
  exit
fi
if [ -z "$ADDR" ]; then
  echo "Enviroment variable(ADDR) is NULL"
  exit
fi
if [ -z "$PREFIX" ]; then
  echo "Enviroment variable(PREFIX) is NULL"
  exit
fi

## Set variable
phy="$PHY"
addr="$ADDR"
prefix="$PREFIX"
br=br-"$PHY"
gw="$GATEWAY"
dns1="$DNS1"

## Configure script
brCfg=/etc/sysconfig/network-scripts/ifcfg-"$br"
phyCfg=/etc/sysconfig/network-scripts/ifcfg-"$phy"

## Generate bridge configure
echo "## Generate by OpenLAN script" > $brCfg
echo "STP=yes" >> $brCfg
echo "DELAY=2" >> $brCfg
echo "TYPE=Bridge" >> $brCfg
echo "DEVICE=$br" >> $brCfg
echo "BOOTPROTO=none" >> $brCfg
if [ -n "$addr" ]; then
  echo "IPADDR=$addr" >> $brCfg
fi
if [ -n "$prefix" ]; then
  echo "PREFIX=$prefix" >> $brCfg
fi
if [ -n "$gw" ]; then
  echo "GATEWAY=$gw" >> $brCfg
fi
if [ -n "$dns1" ]; then
  echo "DNS1=$dns1" >> $brCfg
fi
echo "ONBOOT=yes" >> $brCfg
echo "NM_CONTROLLED=no" >> $brCfg

## Generate physical configure
echo "## Generate by OpenLAN script" > $phyCfg
echo "TYPE=Ethernet" >> $phyCfg
echo "DEVICE=$phy" >> $phyCfg
echo "BOOTPROTO=none" >> $phyCfg
echo "ONBOOT=yes" >> $phyCfg
echo "NM_CONTROLLED=no" >> $phyCfg
echo "BRIDGE=$br" >> $phyCfg
ifdown "$br"; ifdown "$phy"; ifup "$br"; ifup "$phy";

