#!/bin/bash

dir="/etc/openlan/switch"

if [ ! -e "${dir}" ]; then
  exit 0
fi

files=$(find ${dir} -name "*.json")
for i in ${files}; do
    echo "-- Checking ${i}"
    if python -m json.tool "$i" >/dev/null; then
        echo "-- ... success"
    else
        echo "-- ... has error"
    fi
    echo ""
done
