#!/usr/bin/env bash

api=$1
if [ -z "${api}" ] || [ "${api}" == "-h" ]; then
  echo "Usage: $0 <API>"
  echo ""
  echo "API:"
  echo "  lease     display address lease."
  echo "  server    display connection server information."
  echo "  point     display point accessed to switch."
  echo ""
  echo "Project on <https://github.com/danieldin95/openlan-go>."
  exit 0
fi

token=${OL_TOKEN}
if [ -z "${token}" ]; then
  token=$(cat /etc/openlan/switch/token)
fi
url=${OL_URL}
if [ -z "${url}" ]; then
  url="https://localhost:10000/api"
fi

/usr/bin/curl -s -u"${token}": -k -XGET "${url}/${api}"
